$if[$customID==ticket_config-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket.ruby
$elseif[$customID==voltar_botconfig-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Botconfig.ruby
$elseif[$customID==ticket_canais-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket-Canais.ruby
$elseif[$customID==voltar_ticket-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket.ruby
$elseif[$customID==ticket_cargos-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket-Cargos.ruby
$elseif[$customID==ticket_outros-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket-Outros.ruby
$endif
