$if[$customID==ticket_config-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket.ruby
$elseif[$customID==voltar_botconfig-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Botconfig.ruby
$elseif[$customID==ticket_canais-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket-Canais.ruby
$elseif[$customID==voltar_ticket-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket.ruby
$elseif[$customID==ticket_cargos-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket-Cargos.ruby
$elseif[$customID==ticket_outros-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket-Outros.ruby
$elseif[$customID==ticket_categoria-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Categoria-Ticket.ruby
$elseif[$customID==ticket_logs-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Canal-Logs.ruby
$elseif[$customID==ticket_avaliações-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Canal-Avalia%C3%A7%C3%B5es.ruby
$elseif[$customID==setar_categoria_ticket]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Setar-Categoria-Ticket.ruby
$elseif[$customID==setar_canal_logs]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Setar-Canal-Logs.ruby
$endif
