$if[$customID==ticket_config-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket.ruby
$elseif[$customID==voltar_botconfig-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Botconfig.ruby
$elseif[$customID==ticket_canais-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket-Canais.ruby
$elseif[$customID==voltar_ticket-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket.ruby
$elseif[$customID==ticket_cargos-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket-Cargos.ruby
$elseif[$customID==ticket_outros-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Ticket-Outros.ruby
$elseif[$customID==ticket_categoria-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Categoria-Ticket.ruby
$elseif[$customID==ticket_logs-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Canal-Logs.ruby
$elseif[$customID==ticket_avaliações-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Canal-Avalia%C3%A7%C3%B5es.ruby
$elseif[$customID==setar_categoria_ticket]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Setar-Categoria-Ticket.ruby
$elseif[$customID==setar_canal_logs]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Setar-Canal-Logs.ruby
$elseif[$customID==setar_canal_avaliações]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Setar-Canal-Avalia%C3%A7%C3%B5es.ruby
$elseif[$customID==ticket_atendente-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Cargo-Atendente.ruby
$elseif[$customID==ticket_blacklist-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Cargo-Blacklist.ruby
$elseif[$customID==setar_cargo_atendente]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Setar-Cargo-Atendente.ruby
$elseif[$customID==setar_cargo_blacklist]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Setar-Cargo-Blacklist.ruby
$elseif[$customID==ticket_titulo_canal-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Titulo-Canal.ruby
$elseif[$customID==ticket_cor_canal-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Cor-Ticket.ruby
$elseif[$customID==ticket_menssagen-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Ticket/Modal-Mensagem-Ticket.ruby

$elseif[$customID==botlist_config-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Botlist.ruby
$elseif[$customID==voltar_botlist-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Botlist.ruby
$elseif[$customID==botlist_canais-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Botlist-Canais.ruby
$elseif[$customID==botlist_cargos-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Botlist-Cargos.ruby
$elseif[$customID==botlist_outros-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Botlist-Outros.ruby
$elseif[$customID==botlist_canal_addbot-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Modal-Canal-Addbot.ruby
$elseif[$customID==botlist_canal_analises-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Modal-Canal-Analises.ruby
$elseif[$customID==botlist_canal_correios-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Modal-Canal-Correios.ruby
$elseif[$customID==botlist_canal_logs-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Modal-Canal-Logs.ruby
$elseif[$customID==setar_canal_addbot]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Setar-Canal-Addbot.ruby
$elseif[$customID==setar_canal_analises]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Setar-Canal-Analises.ruby
$elseif[$customID==setar_canal_correios]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Setar-Canal-Correios.ruby
$elseif[$customID==setar_canal_logsb]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Botlist/Setar-Canal-Logs.ruby

$elseif[$customID==mod_config-$authorID]
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Modera%C3%A7%C3%A3o/Intera%C3%A7%C3%B5es/Botconfig/Modera%C3%A7%C3%A3o/Mod.ruby

$else
https://raw.githubusercontent.com/Demom23345/Naomidori/main/Comandos/Inexistente.ruby
$endif
